[package]
name = "generic-description-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
